//! Atomic swap: exchange two token amounts between two parties in a single
//! authorized transaction. Both parties must authorize the swap; if either
//! side fails, neither transfer executes.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contracterror, contractimpl, panic_with_error, token, Address, Env};

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    /// A supplied amount was zero or negative.
    InvalidAmount = 1,
}

#[contract]
pub struct AtomicSwap;

#[contractimpl]
impl AtomicSwap {
    /// Swap `amount_a` of `token_a` from `party_a` to `party_b`, and
    /// `amount_b` of `token_b` from `party_b` to `party_a`, atomically.
    ///
    /// Both parties must authorize the call. If either transfer fails the
    /// entire transaction reverts.
    pub fn swap(
        env: Env,
        party_a: Address,
        party_b: Address,
        token_a: Address,
        token_b: Address,
        amount_a: i128,
        amount_b: i128,
    ) {
        if amount_a <= 0 || amount_b <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }

        // Both parties must authorize this specific swap.
        party_a.require_auth();
        party_b.require_auth();

        // Move token A from party_a -> party_b.
        let client_a = token::Client::new(&env, &token_a);
        client_a.transfer(&party_a, &party_b, &amount_a);

        // Move token B from party_b -> party_a.
        let client_b = token::Client::new(&env, &token_b);
        client_b.transfer(&party_b, &party_a, &amount_b);
    }
}

#[cfg(test)]
mod test;
