//! Flash loan pool — lends without collateral inside a single transaction and
//! requires principal + fee back before the call returns.
//!
//! Nothing secures the loan except *atomicity*. The pool transfers the funds
//! out, calls back into the borrower, and then re-reads its own balance. If
//! the borrower did not make the pool whole, the check panics — and that panic
//! unwinds the transfer that funded the loan along with everything the
//! borrower did in between. The pool either ends the call richer by the fee,
//! or the call never happened.
//!
//! Read the security caveats in `README.md` before adapting this. Flash loans
//! are a well-understood attack primitive as much as a useful one, and most of
//! what can go wrong goes wrong in the *contracts around* the pool.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{
    contract, contractclient, contracterror, contractimpl, contracttype, panic_with_error, token,
    Address, Env,
};

/// Fee ceiling in basis points (10%), enforced at construction.
const MAX_FEE_BPS: u32 = 1_000;

/// One hundred percent, in basis points.
const BPS_DENOMINATOR: i128 = 10_000;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    /// A supplied amount was zero or negative.
    InvalidAmount = 1,
    /// The configured fee exceeds `MAX_FEE_BPS`.
    InvalidFee = 2,
    /// The pool holds less than the requested amount.
    InsufficientLiquidity = 3,
    /// The borrower did not return principal + fee before its callback ended.
    NotRepaid = 4,
}

#[contracttype]
pub enum DataKey {
    Admin,
    Token,
    FeeBps,
}

/// The interface a borrower must expose to receive a flash loan.
///
/// `exec` runs with the borrowed funds already credited to the borrower. By
/// the time it returns, `amount + fee` of `token` must be back in `pool` —
/// transferred there by the borrower — or the whole transaction reverts.
///
/// `exec` is a public entrypoint like any other: anyone can call it directly
/// with arguments of their choosing. A borrower must authenticate its caller
/// rather than trusting the values it is handed (see the README).
#[contractclient(name = "FlashLoanReceiverClient")]
pub trait FlashLoanReceiver {
    fn exec(env: Env, pool: Address, token: Address, amount: i128, fee: i128);
}

#[contract]
pub struct FlashLoanPool;

#[contractimpl]
impl FlashLoanPool {
    /// * `admin` — the only address that may withdraw liquidity
    /// * `token` — the SEP-41 token this pool lends
    /// * `fee_bps` — loan fee in basis points (30 = 0.30%), capped at 10%
    pub fn __constructor(env: Env, admin: Address, token: Address, fee_bps: u32) {
        if fee_bps > MAX_FEE_BPS {
            panic_with_error!(&env, Error::InvalidFee);
        }
        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::Token, &token);
        env.storage().instance().set(&DataKey::FeeBps, &fee_bps);
    }

    /// Add liquidity to the pool.
    ///
    /// Anyone may lend to the pool; only the admin may take funds back out.
    /// A real deployment would issue LP shares here — this one keeps the
    /// accounting out of the way of the flash-loan mechanics.
    pub fn deposit(env: Env, from: Address, amount: i128) {
        from.require_auth();
        if amount <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }
        let client = token::Client::new(&env, &Self::token_address(&env));
        client.transfer(&from, env.current_contract_address(), &amount);
    }

    /// Remove liquidity from the pool. Admin only.
    pub fn withdraw(env: Env, to: Address, amount: i128) {
        let admin: Address = env.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();
        if amount <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }
        let client = token::Client::new(&env, &Self::token_address(&env));
        let pool = env.current_contract_address();
        if client.balance(&pool) < amount {
            panic_with_error!(&env, Error::InsufficientLiquidity);
        }
        client.transfer(&pool, &to, &amount);
    }

    /// Lend `amount` to `receiver` for the duration of this call.
    ///
    /// The sequence is:
    ///
    /// 1. snapshot the pool's balance,
    /// 2. transfer `amount` to `receiver`,
    /// 3. call `receiver.exec(..)` — the borrower does whatever it likes,
    /// 4. re-read the balance and require it grew by at least `fee`.
    ///
    /// Step 4 is the *only* thing enforcing repayment. There is no collateral
    /// and no credit check: if the balance is short this panics, and the panic
    /// unwinds step 2 along with every state change the borrower made in step
    /// 3. That is what makes an uncollateralized loan safe to offer.
    ///
    /// Anyone may call this, for any `receiver`. A borrower must therefore be
    /// written to expect loans it did not ask for.
    pub fn flash_loan(env: Env, receiver: Address, amount: i128) {
        if amount <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }

        let token_address = Self::token_address(&env);
        let client = token::Client::new(&env, &token_address);
        let pool = env.current_contract_address();

        // Snapshot before anything moves — this is what step 4 compares to.
        let before = client.balance(&pool);
        if before < amount {
            panic_with_error!(&env, Error::InsufficientLiquidity);
        }
        let fee = Self::fee_for(env.clone(), amount);

        // The pool authorizes moving its own funds by virtue of being the
        // caller of the token contract; no signature is involved.
        client.transfer(&pool, &receiver, &amount);

        // Hand control to the borrower. Everything it does from here —
        // including calls back out to other contracts — happens inside this
        // transaction, and unwinds with it if the check below fails.
        FlashLoanReceiverClient::new(&env, &receiver).exec(&pool, &token_address, &amount, &fee);

        if client.balance(&pool) < before + fee {
            panic_with_error!(&env, Error::NotRepaid);
        }
    }

    /// The fee charged on a loan of `amount`.
    ///
    /// Rounded up, so the pool never loses a stroop to truncation: a fee that
    /// rounds to zero would make small loans free.
    pub fn fee_for(env: Env, amount: i128) -> i128 {
        if amount <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }
        let fee_bps: u32 = env.storage().instance().get(&DataKey::FeeBps).unwrap();
        (amount * i128::from(fee_bps) + BPS_DENOMINATOR - 1) / BPS_DENOMINATOR
    }

    /// Liquidity currently available to lend.
    pub fn balance(env: Env) -> i128 {
        let client = token::Client::new(&env, &Self::token_address(&env));
        client.balance(&env.current_contract_address())
    }

    /// The SEP-41 token this pool lends.
    pub fn token(env: Env) -> Address {
        Self::token_address(&env)
    }

    /// The loan fee, in basis points.
    pub fn fee_bps(env: Env) -> u32 {
        env.storage().instance().get(&DataKey::FeeBps).unwrap()
    }

    /// The address allowed to withdraw liquidity.
    pub fn admin(env: Env) -> Address {
        env.storage().instance().get(&DataKey::Admin).unwrap()
    }
}

impl FlashLoanPool {
    fn token_address(env: &Env) -> Address {
        env.storage().instance().get(&DataKey::Token).unwrap()
    }
}

#[cfg(test)]
mod test;
