# typed: false
# frozen_string_literal: true

# Homebrew formula for soroban-forge.
# Hosted in the tap repo: https://github.com/soroban-forge-labs/homebrew-tap
#
# DO NOT EDIT BY HAND — generated by `scripts/update-homebrew-formula.sh` in
# the main repository. The copy checked in there carries placeholder checksums;
# the `release` workflow re-renders it with the real ones on every tag and
# publishes that version to the tap.
class SorobanForge < Formula
  desc "Scaffolding, test-harness and CI toolkit for Soroban smart contracts on Stellar"
  homepage "https://github.com/soroban-forge-labs/soroban-forge"
  version "0.1.0"
  license "Apache-2.0"

  # ---------------------------------------------------------------------------
  # Release archives — one per supported platform.
  # Each archive is a .tar.gz containing a single pre-compiled `soroban-forge`
  # binary, so installing needs no Rust toolchain and no build step.
  # ---------------------------------------------------------------------------

  on_macos do
    on_arm do
      url "https://github.com/soroban-forge-labs/soroban-forge/releases/download/v#{version}/soroban-forge-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_SHA256_AARCH64_APPLE_DARWIN"
    end

    on_intel do
      url "https://github.com/soroban-forge-labs/soroban-forge/releases/download/v#{version}/soroban-forge-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_SHA256_X86_64_APPLE_DARWIN"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/soroban-forge-labs/soroban-forge/releases/download/v#{version}/soroban-forge-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER_SHA256_AARCH64_UNKNOWN_LINUX_GNU"
    end

    on_intel do
      url "https://github.com/soroban-forge-labs/soroban-forge/releases/download/v#{version}/soroban-forge-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER_SHA256_X86_64_UNKNOWN_LINUX_GNU"
    end
  end

  def install
    bin.install "soroban-forge"

    # `soroban-forge completions <shell>` writes the script to stdout. The CLI
    # handles this before any network or config work, so it is safe to run
    # inside Homebrew's sandbox.
    generate_completions_from_executable(bin/"soroban-forge", "completions")

    # `soroban-forge man --out-dir DIR` writes one roff page per subcommand.
    # Best-effort via `quiet_system`: man pages are a convenience and must
    # never be the reason `brew install` fails. The env var suppresses the
    # background release check so the sandboxed build never needs the network.
    man_generated = with_env("SOROBAN_FORGE_NO_UPDATE_CHECK" => "1") do
      quiet_system bin/"soroban-forge", "man", "--out-dir", "manpages"
    end
    man1.install Dir["manpages/*.1"] if man_generated
  end

  test do
    # The binary must report the version this formula claims to have installed.
    assert_match version.to_s, shell_output("#{bin}/soroban-forge --version")

    # Completions must generate, since `install` depends on them.
    assert_match "soroban-forge", shell_output("#{bin}/soroban-forge completions bash")

    # And the CLI must actually scaffold a project. `--no-git` keeps the test
    # hermetic (no git identity required) and the env var suppresses the
    # background release check so the test never needs the network.
    with_env("SOROBAN_FORGE_NO_UPDATE_CHECK" => "1") do
      system bin/"soroban-forge", "new", "demo", "--template", "hello-world", "--no-git"
    end
    assert_predicate testpath/"demo/Cargo.toml", :exist?
  end
end
