//! Criterion benchmark generation (issue #235).
//!
//! Budget tests assert a ceiling: they catch the moment a cost crosses a line,
//! and say nothing until then. A benchmark records the number every run, so a
//! change that adds 20% to an entrypoint is visible immediately instead of
//! whenever it happens to breach the budget. The two are complementary — the
//! budget test gates, the bench tracks.

use crate::detect::{ContractInfo, MethodInfo};
use soroban_forge_core::render::{render_str, Vars};

/// `benches/forge_bench.rs`, the criterion harness.
pub const BENCH_RS: &str = r#"//! Generated by `soroban-forge test-init --bench`.
//!
//! Criterion benchmarks for the contract's entrypoints. Where the budget test
//! in `tests/forge_budget.rs` gates a ceiling, these track the cost over time:
//!
//!   cargo bench                        # run every benchmark
//!   cargo bench -- <entrypoint>        # run one
//!   cargo bench -- --save-baseline main
//!   cargo bench -- --baseline main     # compare a branch against it
//!
//! Criterion writes reports to `target/criterion/`.
//!
//! Note that these measure host wall-clock time in the test environment, not
//! on-chain CPU instructions. For the metered numbers that decide whether a
//! transaction fits in a ledger, use the budget test. Wall-clock is still the
//! right tool for spotting a regression trend, because it moves with the same
//! work the metered cost does.

use criterion::{criterion_group, criterion_main, Criterion};
"#;

/// One benchmark function. Receives `contract_type`, `fn_name`,
/// `contract_args`, `entrypoint` and `entrypoint_args`.
pub const BENCH_FN: &str = r#"
fn bench_{{fn_name}}_{{entrypoint}}(c: &mut Criterion) {
    c.bench_function("{{fn_name}}::{{entrypoint}}", |b| {
        b.iter(|| {
            // The environment is rebuilt per iteration on purpose: a contract
            // whose cost grows with accumulated state would otherwise be
            // measured against whatever the previous iterations left behind.
            let env = common::test_env();
            let contract_id = env.register({{contract_type}}, {{contract_args}});
            let client = {{contract_type}}Client::new(&env, &contract_id);
            env.mock_all_auths();
            criterion::black_box(client.{{entrypoint}}({{entrypoint_args}}));
        })
    });
}
"#;

/// The `[[bench]]` target and criterion dev-dependency a scaffolded project
/// needs for `cargo bench` to find the harness.
pub const BENCH_CARGO_FRAGMENT: &str = r#"
[dev-dependencies]
criterion = { version = "0.5", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name = "forge_bench"
harness = false
"#;

/// Entrypoints worth benchmarking.
///
/// `__constructor` runs at registration rather than through the client, and a
/// method whose arguments cannot be defaulted would not compile, so both are
/// skipped rather than emitted broken.
pub fn benchable_methods(info: &ContractInfo) -> Vec<&MethodInfo> {
    info.methods
        .iter()
        .filter(|m| m.name != "__constructor")
        .collect()
}

/// Client call arguments, defaulted from each parameter's type.
fn bench_call_args(method: &MethodInfo) -> String {
    method
        .args
        .iter()
        .map(|(_, ty)| format!("&{}", crate::detect::map_type_to_default(ty)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render `benches/forge_bench.rs`.
///
/// Returns an empty string when the contract has no benchmarkable entrypoint,
/// so `--bench` on a contract with nothing to measure does not leave behind a
/// `benches/` target that fails to build.
pub fn build_bench(info: &ContractInfo) -> String {
    let methods = benchable_methods(info);
    if methods.is_empty() || info.contract_types.is_empty() {
        return String::new();
    }

    let mut out = String::from(BENCH_RS);
    out.push_str(&format!(
        "use {}::{{ {} }};\n",
        info.crate_name,
        info.contract_types
            .iter()
            .flat_map(|ct| [ct.clone(), format!("{ct}Client")])
            .collect::<Vec<_>>()
            .join(", ")
    ));
    // Benches are their own crate root, so the fixtures module is included
    // rather than declared as a sibling of the integration tests.
    out.push_str("\n#[path = \"../tests/common/mod.rs\"]\nmod common;\n");

    let mut group_members: Vec<String> = Vec::new();

    for contract_type in &info.contract_types {
        let fn_name = crate::to_snake_case(contract_type);
        for method in &methods {
            let mut vars = Vars::new();
            vars.insert("contract_type".into(), contract_type.clone());
            vars.insert("fn_name".into(), fn_name.clone());
            vars.insert("contract_args".into(), info.constructor_args.clone());
            vars.insert("entrypoint".into(), method.name.clone());
            vars.insert("entrypoint_args".into(), bench_call_args(method));
            out.push_str(&render_str(BENCH_FN, &vars));
            group_members.push(format!("bench_{fn_name}_{}", method.name));
        }
    }

    out.push_str(&format!(
        "\ncriterion_group!(forge_benches, {});\ncriterion_main!(forge_benches);\n",
        group_members.join(", ")
    ));

    out
}

/// Returns true if the manifest declares `criterion` as a dependency or dev-dependency.
pub fn has_criterion_dependency(manifest: &str) -> bool {
    if let Ok(val) = toml::from_str::<toml::Value>(manifest) {
        if let Some(dev_deps) = val.get("dev-dependencies").and_then(|d| d.as_table()) {
            if dev_deps.contains_key("criterion") {
                return true;
            }
        }
        if let Some(deps) = val.get("dependencies").and_then(|d| d.as_table()) {
            if deps.contains_key("criterion") {
                return true;
            }
        }
        if let Some(target) = val.get("target").and_then(|t| t.as_table()) {
            for target_val in target.values() {
                if let Some(target_dev_deps) = target_val.get("dev-dependencies").and_then(|d| d.as_table()) {
                    if target_dev_deps.contains_key("criterion") {
                        return true;
                    }
                }
            }
        }
    }
    manifest.lines().any(|line| {
        let trimmed = line.trim();
        trimmed.starts_with("criterion =") || trimmed.starts_with("criterion=")
    }) || manifest.contains("[dev-dependencies.criterion]")
}

/// Returns true if the manifest declares a `forge_bench` bench target.
pub fn has_forge_bench_target(manifest: &str) -> bool {
    if let Ok(val) = toml::from_str::<toml::Value>(manifest) {
        if let Some(benches) = val.get("bench").and_then(|b| b.as_array()) {
            if benches.iter().any(|b| b.get("name").and_then(|n| n.as_str()) == Some("forge_bench")) {
                return true;
            }
        }
    }
    manifest.contains("name = \"forge_bench\"") || manifest.contains("name = 'forge_bench'")
}

/// The exact snippet to add to `Cargo.toml` for criterion and the bench target.
pub fn bench_cargo_snippet() -> &'static str {
    BENCH_CARGO_FRAGMENT.trim()
}

/// Appends the `[[bench]]` target and/or criterion dev-dependency to the
/// project's `Cargo.toml` if either is missing.
///
/// Returns `Some(updated)` when the manifest was changed, or `None` if both
/// the `criterion` dependency and `forge_bench` target are already configured.
pub fn ensure_bench_target(manifest: &str) -> Option<String> {
    let has_crit = has_criterion_dependency(manifest);
    let has_bench = has_forge_bench_target(manifest);

    if has_crit && has_bench {
        return None;
    }

    let mut updated = manifest.trim_end().to_string();
    updated.push('\n');

    const CRITERION_LINE: &str = "criterion = { version = \"0.5\", default-features = false, features = [\"cargo_bench_support\"] }";
    const BENCH_SECTION: &str = "[[bench]]\nname = \"forge_bench\"\nharness = false";

    if !has_crit && !has_bench {
        if manifest.contains("[dev-dependencies]") {
            updated.push_str(&format!("\n{CRITERION_LINE}\n\n{BENCH_SECTION}\n"));
        } else {
            updated.push_str(&format!("\n[dev-dependencies]\n{CRITERION_LINE}\n\n{BENCH_SECTION}\n"));
        }
    } else if !has_crit && has_bench {
        if manifest.contains("[dev-dependencies]") {
            updated.push_str(&format!("\n{CRITERION_LINE}\n"));
        } else {
            updated.push_str(&format!("\n[dev-dependencies]\n{CRITERION_LINE}\n"));
        }
    } else if has_crit && !has_bench {
        updated.push_str(&format!("\n{BENCH_SECTION}\n"));
    }

    Some(updated)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn method(name: &str, args: &[(&str, &str)]) -> MethodInfo {
        MethodInfo {
            name: name.to_string(),
            args: args
                .iter()
                .map(|(n, t)| (n.to_string(), t.to_string()))
                .collect(),
        }
    }

    fn info_with(methods: Vec<MethodInfo>) -> ContractInfo {
        ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_types: vec!["DemoContract".into()],
            has_constructor: false,
            has_testutils: true,
            constructor_args: "()".into(),
            has_proptest: false,
            methods,
            constructor_arg_types: None,
            events: Vec::new(),
            has_contractevent: false,
            has_token_deps: false,
            token_param_names: Vec::new(),
            init_method: None,
            has_persistent_storage: false,
            has_instance_storage: false,
            has_temporary_storage: false,
        }
    }

    #[test]
    fn skips_the_constructor() {
        let info = info_with(vec![
            method("__constructor", &[("admin", "Address")]),
            method("increment", &[]),
        ]);
        let names: Vec<_> = benchable_methods(&info).iter().map(|m| &m.name).collect();
        assert_eq!(names, vec!["increment"]);
    }

    #[test]
    fn emits_a_criterion_main_and_one_function_per_entrypoint() {
        let info = info_with(vec![
            method("increment", &[]),
            method("mint", &[("to", "Address"), ("amount", "i128")]),
        ]);
        let rendered = build_bench(&info);

        assert!(rendered.contains("fn bench_demo_contract_increment"));
        assert!(rendered.contains("fn bench_demo_contract_mint"));
        assert!(rendered.contains(
            "criterion_group!(forge_benches, bench_demo_contract_increment, bench_demo_contract_mint);"
        ));
        assert!(rendered.contains("criterion_main!(forge_benches);"));
    }

    #[test]
    fn defaults_entrypoint_arguments() {
        let info = info_with(vec![method(
            "mint",
            &[("to", "Address"), ("amount", "i128")],
        )]);
        let rendered = build_bench(&info);
        assert!(rendered.contains("client.mint(&common::new_account(&env), &0_i128)"));
    }

    #[test]
    fn reuses_the_generated_fixtures_module() {
        let info = info_with(vec![method("increment", &[])]);
        let rendered = build_bench(&info);
        assert!(rendered.contains("#[path = \"../tests/common/mod.rs\"]"));
    }

    #[test]
    fn emits_nothing_when_there_is_nothing_to_measure() {
        let info = info_with(vec![method("__constructor", &[])]);
        assert!(build_bench(&info).is_empty());
    }

    #[test]
    fn adds_the_bench_target_to_a_manifest() {
        let manifest = "[package]\nname = \"demo\"\n";
        let updated = ensure_bench_target(manifest).expect("manifest changed");
        assert!(updated.contains("[[bench]]"));
        assert!(updated.contains("harness = false"));
        assert!(updated.contains("criterion"));
    }

    #[test]
    fn reuses_an_existing_dev_dependencies_section() {
        let manifest = "[package]\nname = \"demo\"\n\n[dev-dependencies]\nproptest = \"1\"\n";
        let updated = ensure_bench_target(manifest).expect("manifest changed");
        // A second [dev-dependencies] table would make cargo reject the file.
        assert_eq!(updated.matches("[dev-dependencies]").count(), 1);
        assert!(updated.contains("criterion"));
    }

    #[test]
    fn is_idempotent() {
        let manifest = "[package]\nname = \"demo\"\n";
        let once = ensure_bench_target(manifest).expect("manifest changed");
        assert!(ensure_bench_target(&once).is_none());
    }

    #[test]
    fn bench_target_already_configured_is_unchanged() {
        let manifest = r#"[package]
name = "demo"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "forge_bench"
harness = false
"#;
        assert!(ensure_bench_target(manifest).is_none());
    }

    #[test]
    fn missing_config_adds_both_criterion_and_bench() {
        let manifest = r#"[package]
name = "demo"
"#;
        let updated = ensure_bench_target(manifest).expect("manifest should be updated");
        assert!(updated.contains("[dev-dependencies]"));
        assert!(updated.contains("criterion ="));
        assert!(updated.contains("[[bench]]"));
        assert!(updated.contains("name = \"forge_bench\""));
    }

    #[test]
    fn missing_criterion_only_adds_criterion() {
        let manifest = r#"[package]
name = "demo"

[[bench]]
name = "forge_bench"
harness = false
"#;
        let updated = ensure_bench_target(manifest).expect("manifest should add missing criterion");
        assert!(updated.contains("criterion ="));
        assert_eq!(updated.matches("name = \"forge_bench\"").count(), 1);
    }

    #[test]
    fn missing_bench_only_adds_bench() {
        let manifest = r#"[package]
name = "demo"

[dev-dependencies]
criterion = "0.5"
"#;
        let updated = ensure_bench_target(manifest).expect("manifest should add missing bench");
        assert!(updated.contains("[[bench]]"));
        assert!(updated.contains("name = \"forge_bench\""));
        assert_eq!(updated.matches("[dev-dependencies]").count(), 1);
        assert_eq!(updated.matches("criterion =").count(), 1);
    }

    #[test]
    fn snippet_provides_exact_cargo_fragment() {
        let snippet = bench_cargo_snippet();
        assert!(snippet.contains("criterion ="));
        assert!(snippet.contains("[[bench]]"));
        assert!(snippet.contains("name = \"forge_bench\""));
    }

    #[test]
    fn write_bench_files_updates_unconfigured_manifest() {
        let dir = tempfile::tempdir().unwrap();
        let manifest_path = dir.path().join("Cargo.toml");
        std::fs::write(&manifest_path, "[package]\nname = \"test-contract\"\n").unwrap();
        let info = info_with(vec![method("increment", &[])]);

        let written = crate::write_bench_files(dir.path(), &info, false).unwrap();
        assert!(written.contains(&"benches/forge_bench.rs"));
        assert!(written.contains(&"Cargo.toml"));

        let updated_manifest = std::fs::read_to_string(&manifest_path).unwrap();
        assert!(updated_manifest.contains("criterion ="));
        assert!(updated_manifest.contains("[[bench]]"));
    }

    #[test]
    fn write_bench_files_skips_already_configured_manifest() {
        let dir = tempfile::tempdir().unwrap();
        let manifest_path = dir.path().join("Cargo.toml");
        std::fs::write(
            &manifest_path,
            "[package]\nname = \"test-contract\"\n\n[dev-dependencies]\ncriterion = \"0.5\"\n\n[[bench]]\nname = \"forge_bench\"\nharness = false\n",
        )
        .unwrap();
        let info = info_with(vec![method("increment", &[])]);

        let written = crate::write_bench_files(dir.path(), &info, false).unwrap();
        assert!(written.contains(&"benches/forge_bench.rs"));
        assert!(!written.contains(&"Cargo.toml"));
    }
}
