//! Round-trip tests for container-typed entrypoint arguments (issue #236).
//!
//! `Option`, `Vec` and `Map` arguments are the ones most often mis-encoded:
//! the host and the contract disagree about how an empty collection or a
//! `None` is represented, and the failure shows up as a silently wrong value
//! rather than a panic. Generating a test that pushes empty, single- and
//! multi-element values through each such entrypoint turns that class of bug
//! into a build failure.

use crate::detect::{ContractInfo, MethodInfo};
use crate::to_snake_case;
use soroban_forge_core::render::{render_str, Vars};

/// Header of the generated round-trip test file.
pub const ROUNDTRIP_TEST_RS: &str = r#"//! Generated by `soroban-forge test-init`. Round-trips container arguments.
//!
//! `Option`, `Vec` and `Map` arguments are the ones most often mis-encoded —
//! the empty case especially, where the host and the contract can disagree
//! about the representation and the call returns a plausible wrong value
//! instead of failing. Each test below passes an empty, a single-element and
//! a multi-element value through one entrypoint.
//!
//! Entrypoints that return their container argument are asserted on directly.
//! For the rest these are smoke tests: they prove the call encodes, decodes
//! and does not trap. Replace the `let _ =` with an assertion against whatever
//! the entrypoint actually does with the value.

mod common;
"#;

/// One round-trip test. Receives `contract_type`, `fn_name`, `entrypoint`,
/// `arg_name`, `case`, `call_args` and `binding`.
pub const ROUNDTRIP_TEST_FN: &str = r#"
#[test]
fn {{fn_name}}_{{entrypoint}}_roundtrips_{{case}}_{{arg_name}}() {
    let env = common::test_env();
    let contract_id = env.register({{contract_type}}, {{contract_args}});
    let client = {{contract_type}}Client::new(&env, &contract_id);

{{binding}}
    let _ = client.{{entrypoint}}({{call_args}});
}
"#;

/// A container argument found on an entrypoint.
#[derive(Debug, Clone, PartialEq)]
pub struct ContainerArg {
    /// Entrypoint the argument belongs to.
    pub method: String,
    /// Argument name, e.g. `recipients`.
    pub name: String,
    /// The container's shape.
    pub kind: ContainerKind,
    /// Zero-based position in the method's argument list.
    pub position: usize,
}

/// Which container an argument uses. The element types are kept as written so
/// the generated literals can name them.
#[derive(Debug, Clone, PartialEq)]
pub enum ContainerKind {
    /// `Option<T>`.
    Option { inner: String },
    /// `Vec<T>`.
    Vec { element: String },
    /// `Map<K, V>`.
    Map { key: String, value: String },
}

/// Strips references and lifetimes so `&'a Vec<Address>` matches as `Vec`.
fn normalize(ty: &str) -> String {
    ty.replace('&', "")
        .replace("'a", "")
        .replace("mut ", "")
        .trim()
        .to_string()
}

/// Splits `A, B` on the top-level comma only, so `Map<Address, Vec<u32>>`
/// yields `Address` and `Vec<u32>` rather than splitting inside the nested
/// generic.
fn split_top_level(args: &str) -> Vec<String> {
    let mut parts = Vec::new();
    let mut depth = 0usize;
    let mut current = String::new();

    for ch in args.chars() {
        match ch {
            '<' => {
                depth += 1;
                current.push(ch);
            }
            '>' => {
                depth = depth.saturating_sub(1);
                current.push(ch);
            }
            ',' if depth == 0 => {
                parts.push(current.trim().to_string());
                current.clear();
            }
            _ => current.push(ch),
        }
    }

    if !current.trim().is_empty() {
        parts.push(current.trim().to_string());
    }
    parts
}

/// Extracts the generic payload of `Wrapper<...>`, honouring nesting.
fn generic_args(ty: &str, wrapper: &str) -> Option<String> {
    let ty = normalize(ty);
    // Match `Vec<..>` and `soroban_sdk::Vec<..>` alike.
    let head = ty.split('<').next()?.trim().to_string();
    if head != wrapper && !head.ends_with(&format!("::{wrapper}")) {
        return None;
    }
    let start = ty.find('<')?;
    let end = ty.rfind('>')?;
    if end <= start {
        return None;
    }
    Some(ty[start + 1..end].trim().to_string())
}

/// Classifies a single argument type, or `None` when it is not a container.
pub fn classify(ty: &str) -> Option<ContainerKind> {
    if let Some(inner) = generic_args(ty, "Option") {
        return Some(ContainerKind::Option { inner });
    }
    if let Some(element) = generic_args(ty, "Vec") {
        return Some(ContainerKind::Vec { element });
    }
    if let Some(payload) = generic_args(ty, "Map") {
        let parts = split_top_level(&payload);
        if parts.len() == 2 {
            return Some(ContainerKind::Map {
                key: parts[0].clone(),
                value: parts[1].clone(),
            });
        }
    }
    None
}

/// Finds every container argument across the contract's entrypoints.
pub fn find_container_args(methods: &[MethodInfo]) -> Vec<ContainerArg> {
    let mut found = Vec::new();
    for method in methods {
        // `__constructor` runs at registration, not through the client, so it
        // cannot be round-tripped the way an entrypoint can.
        if method.name == "__constructor" {
            continue;
        }
        for (position, (name, ty)) in method.args.iter().enumerate() {
            if let Some(kind) = classify(ty) {
                found.push(ContainerArg {
                    method: method.name.clone(),
                    name: name.clone(),
                    kind,
                    position,
                });
            }
        }
    }
    found
}

/// True for `u8`..`u128` / `i8`..`i128`, whose literals take a type suffix.
fn is_integer_type(ty: &str) -> bool {
    ty.strip_prefix('u')
        .or_else(|| ty.strip_prefix('i'))
        .is_some_and(|rest| !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit()))
}

/// A sample element of `ty`, distinct per `seed` so a multi-element collection
/// does not collapse to one repeated value.
fn sample_element(ty: &str, seed: usize) -> String {
    let ty = normalize(ty);
    if ty.contains("Address") {
        "common::new_account(&env)".to_string()
    } else if ty == "bool" {
        if seed % 2 == 0 { "true" } else { "false" }.to_string()
    } else if ty.ends_with("String") {
        format!("soroban_sdk::String::from_str(&env, \"sample{seed}\")")
    } else if ty.ends_with("Symbol") {
        format!("soroban_sdk::Symbol::new(&env, \"sample{seed}\")")
    } else if ty.ends_with("Bytes") {
        format!("soroban_sdk::Bytes::from_array(&env, &[{seed}u8])")
    } else if is_integer_type(&ty) {
        // `1_u32`, `2_i128` — the suffix keeps the literal unambiguous.
        format!("{seed}_{ty}")
    } else {
        // Unknown element type: `Default::default()` keeps the file compiling
        // and the reader can see what to replace.
        "Default::default()".to_string()
    }
}

/// The three cases every container argument is exercised with.
const CASES: [&str; 3] = ["empty", "single", "multi"];

/// Renders the literal for `kind` in the given case, plus a short comment.
fn literal(kind: &ContainerKind, case: &str) -> String {
    match kind {
        ContainerKind::Option { inner } => match case {
            "empty" => "None".to_string(),
            // An Option has no "multi": the second populated case still carries
            // one value, with a different element so it is not a copy of
            // `single`.
            "single" => format!("Some({})", sample_element(inner, 1)),
            _ => format!("Some({})", sample_element(inner, 2)),
        },
        ContainerKind::Vec { element } => match case {
            "empty" => "soroban_sdk::vec![&env]".to_string(),
            "single" => format!("soroban_sdk::vec![&env, {}]", sample_element(element, 1)),
            _ => format!(
                "soroban_sdk::vec![&env, {}, {}, {}]",
                sample_element(element, 1),
                sample_element(element, 2),
                sample_element(element, 3),
            ),
        },
        ContainerKind::Map { key, value } => match case {
            "empty" => "soroban_sdk::map![&env]".to_string(),
            "single" => format!(
                "soroban_sdk::map![&env, ({}, {})]",
                sample_element(key, 1),
                sample_element(value, 1),
            ),
            _ => format!(
                "soroban_sdk::map![&env, ({}, {}), ({}, {})]",
                sample_element(key, 1),
                sample_element(value, 1),
                sample_element(key, 2),
                sample_element(value, 2),
            ),
        },
    }
}

/// Builds the call argument list, substituting the container literal at
/// `position` and defaults elsewhere. Soroban clients take arguments by
/// reference, hence the `&` on each.
fn call_args(method: &MethodInfo, arg: &ContainerArg, binding_name: &str) -> String {
    method
        .args
        .iter()
        .enumerate()
        .map(|(i, (_, ty))| {
            if i == arg.position {
                format!("&{binding_name}")
            } else {
                format!("&{}", crate::detect::map_type_to_default(ty))
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render `tests/forge_roundtrip.rs`. Returns an empty string when no
/// entrypoint takes a container argument, so the file is only written for
/// contracts it says something about.
pub fn build_roundtrip_tests(info: &ContractInfo) -> String {
    let args = find_container_args(&info.methods);
    if args.is_empty() {
        return String::new();
    }

    let mut out = String::from(ROUNDTRIP_TEST_RS);
    out.push_str(&format!(
        "use {}::{{ {} }};\n",
        info.crate_name,
        info.contract_types
            .iter()
            .flat_map(|ct| [ct.clone(), format!("{ct}Client")])
            .collect::<Vec<_>>()
            .join(", ")
    ));

    for contract_type in &info.contract_types {
        for arg in &args {
            let Some(method) = info.methods.iter().find(|m| m.name == arg.method) else {
                continue;
            };

            for case in CASES {
                // An Option only has two distinct shapes; skip the third so the
                // file does not carry a duplicate test.
                if matches!(arg.kind, ContainerKind::Option { .. }) && case == "multi" {
                    continue;
                }

                let binding_name = format!("{}_value", arg.name);
                let binding = format!("    let {binding_name} = {};", literal(&arg.kind, case));

                let mut vars = Vars::new();
                vars.insert("contract_type".into(), contract_type.clone());
                vars.insert("fn_name".into(), to_snake_case(contract_type));
                vars.insert("contract_args".into(), info.constructor_args.clone());
                vars.insert("entrypoint".into(), arg.method.clone());
                vars.insert("arg_name".into(), arg.name.clone());
                vars.insert("case".into(), case.to_string());
                vars.insert("binding".into(), binding);
                vars.insert("call_args".into(), call_args(method, arg, &binding_name));
                out.push_str(&render_str(ROUNDTRIP_TEST_FN, &vars));
            }
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn method(name: &str, args: &[(&str, &str)]) -> MethodInfo {
        MethodInfo {
            name: name.to_string(),
            args: args
                .iter()
                .map(|(n, t)| (n.to_string(), t.to_string()))
                .collect(),
        }
    }

    #[test]
    fn classifies_each_container() {
        assert_eq!(
            classify("Option<Address>"),
            Some(ContainerKind::Option {
                inner: "Address".into()
            })
        );
        assert_eq!(
            classify("Vec<u32>"),
            Some(ContainerKind::Vec {
                element: "u32".into()
            })
        );
        assert_eq!(
            classify("Map<Address, i128>"),
            Some(ContainerKind::Map {
                key: "Address".into(),
                value: "i128".into()
            })
        );
    }

    #[test]
    fn classifies_fully_qualified_and_referenced_types() {
        assert!(matches!(
            classify("soroban_sdk::Vec<Address>"),
            Some(ContainerKind::Vec { .. })
        ));
        assert!(matches!(
            classify("&Vec<Address>"),
            Some(ContainerKind::Vec { .. })
        ));
    }

    #[test]
    fn does_not_split_nested_generics() {
        // The comma inside `Vec<u32>` must not be mistaken for the Map's.
        assert_eq!(
            classify("Map<Address, Vec<u32>>"),
            Some(ContainerKind::Map {
                key: "Address".into(),
                value: "Vec<u32>".into()
            })
        );
    }

    #[test]
    fn ignores_scalars() {
        assert_eq!(classify("Address"), None);
        assert_eq!(classify("i128"), None);
        assert_eq!(classify("String"), None);
    }

    #[test]
    fn finds_container_args_and_skips_the_constructor() {
        let methods = vec![
            method("__constructor", &[("admins", "Vec<Address>")]),
            method("airdrop", &[("to", "Address"), ("amounts", "Vec<i128>")]),
            method("noop", &[("n", "u32")]),
        ];
        let found = find_container_args(&methods);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].method, "airdrop");
        assert_eq!(found[0].name, "amounts");
        assert_eq!(found[0].position, 1);
    }

    #[test]
    fn empty_case_is_always_covered() {
        let vec_kind = ContainerKind::Vec {
            element: "u32".into(),
        };
        assert_eq!(literal(&vec_kind, "empty"), "soroban_sdk::vec![&env]");
        assert_eq!(
            literal(
                &ContainerKind::Option {
                    inner: "u32".into()
                },
                "empty"
            ),
            "None"
        );
        assert_eq!(
            literal(
                &ContainerKind::Map {
                    key: "Address".into(),
                    value: "i128".into()
                },
                "empty"
            ),
            "soroban_sdk::map![&env]"
        );
    }

    #[test]
    fn multi_case_uses_distinct_elements() {
        let kind = ContainerKind::Vec {
            element: "u32".into(),
        };
        let rendered = literal(&kind, "multi");
        assert!(rendered.contains("1_u32"));
        assert!(rendered.contains("2_u32"));
        assert!(rendered.contains("3_u32"));
    }

    #[test]
    fn call_args_substitutes_only_the_container_position() {
        let m = method("airdrop", &[("to", "Address"), ("amounts", "Vec<i128>")]);
        let arg = ContainerArg {
            method: "airdrop".into(),
            name: "amounts".into(),
            kind: ContainerKind::Vec {
                element: "i128".into(),
            },
            position: 1,
        };
        let rendered = call_args(&m, &arg, "amounts_value");
        assert_eq!(rendered, "&common::new_account(&env), &amounts_value");
    }
}
