//! An allowlist-gated token where transfers are restricted to addresses
//! approved by an admin.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype, panic_with_error, token, Address, Env,
    Map,
};

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    /// Caller is not the admin.
    NotAdmin = 1,
    /// Address is not on the allowlist.
    NotAllowed = 2,
    /// Amount must be positive.
    InvalidAmount = 3,
    /// Insufficient balance.
    InsufficientBalance = 4,
}

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    Admin,
    Allowlist,
    Balance(Address),
    TotalSupply,
}

fn get_admin(env: &Env) -> Address {
    env.storage().instance().get(&DataKey::Admin).unwrap()
}

fn is_allowed(env: &Env, addr: &Address) -> bool {
    let list: Map<Address, bool> = env
        .storage()
        .instance()
        .get(&DataKey::Allowlist)
        .unwrap_or(Map::new(env));
    list.get(addr.clone()).unwrap_or(false)
}

fn get_balance(env: &Env, addr: &Address) -> i128 {
    env.storage()
        .persistent()
        .get(&DataKey::Balance(addr.clone()))
        .unwrap_or(0)
}

fn set_balance(env: &Env, addr: &Address, amount: i128) {
    env.storage()
        .persistent()
        .set(&DataKey::Balance(addr.clone()), &amount);
}

#[contract]
pub struct AllowlistToken;

#[contractimpl]
impl AllowlistToken {
    /// Initialize the token with an admin.
    pub fn __constructor(env: Env, admin: Address) {
        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage()
            .instance()
            .set(&DataKey::Allowlist, &Map::<Address, bool>::new(&env));
        env.storage().instance().set(&DataKey::TotalSupply, &0i128);
    }

    /// Add an address to the allowlist. Admin only.
    pub fn add_to_allowlist(env: Env, admin: Address, addr: Address) {
        admin.require_auth();
        if admin != get_admin(&env) {
            panic_with_error!(&env, Error::NotAdmin);
        }
        let mut list: Map<Address, bool> = env
            .storage()
            .instance()
            .get(&DataKey::Allowlist)
            .unwrap_or(Map::new(&env));
        list.set(addr, true);
        env.storage().instance().set(&DataKey::Allowlist, &list);
    }

    /// Remove an address from the allowlist. Admin only.
    pub fn remove_from_allowlist(env: Env, admin: Address, addr: Address) {
        admin.require_auth();
        if admin != get_admin(&env) {
            panic_with_error!(&env, Error::NotAdmin);
        }
        let mut list: Map<Address, bool> = env
            .storage()
            .instance()
            .get(&DataKey::Allowlist)
            .unwrap_or(Map::new(&env));
        list.set(addr, false);
        env.storage().instance().set(&DataKey::Allowlist, &list);
    }

    /// Check if an address is on the allowlist.
    pub fn is_allowed(env: Env, addr: Address) -> bool {
        is_allowed(&env, &addr)
    }

    /// Mint tokens to an allowlisted address. Admin only.
    pub fn mint(env: Env, admin: Address, to: Address, amount: i128) {
        admin.require_auth();
        if admin != get_admin(&env) {
            panic_with_error!(&env, Error::NotAdmin);
        }
        if amount <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }
        if !is_allowed(&env, &to) {
            panic_with_error!(&env, Error::NotAllowed);
        }
        set_balance(&env, &to, get_balance(&env, &to) + amount);
        let supply: i128 = env
            .storage()
            .instance()
            .get(&DataKey::TotalSupply)
            .unwrap_or(0);
        env.storage()
            .instance()
            .set(&DataKey::TotalSupply, &(supply + amount));
    }

    /// Transfer tokens between two allowlisted addresses.
    pub fn transfer(env: Env, from: Address, to: Address, amount: i128) {
        from.require_auth();
        if amount <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }
        if !is_allowed(&env, &from) {
            panic_with_error!(&env, Error::NotAllowed);
        }
        if !is_allowed(&env, &to) {
            panic_with_error!(&env, Error::NotAllowed);
        }
        let from_bal = get_balance(&env, &from);
        if from_bal < amount {
            panic_with_error!(&env, Error::InsufficientBalance);
        }
        set_balance(&env, &from, from_bal - amount);
        set_balance(&env, &to, get_balance(&env, &to) + amount);
    }

    /// Get the balance of an address.
    pub fn balance(env: Env, addr: Address) -> i128 {
        get_balance(&env, &addr)
    }

    /// Get the total supply.
    pub fn total_supply(env: Env) -> i128 {
        env.storage()
            .instance()
            .get(&DataKey::TotalSupply)
            .unwrap_or(0)
    }
}

#[cfg(test)]
mod test;
