//! Token faucet dispensing a fixed amount per address with a cooldown.
//!
//! * **Dispense** — any address may call `claim` to receive a fixed
//!   `amount_per_claim` of the configured token.
//! * **Cooldown** — an address must wait `cooldown_seconds` between
//!   successive claims; claiming before the cooldown elapses panics.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, token, Address, Env};

#[contracttype]
pub enum DataKey {
    Admin,
    Token,
    AmountPerClaim,
    CooldownSeconds,
    LastClaim(Address),
}

#[contract]
pub struct FaucetContract;

#[contractimpl]
impl FaucetContract {
    /// Initialize the faucet.
    ///
    /// * `admin` — address that funds the faucet with tokens
    /// * `token` — contract address of the SEP-41 token to dispense
    /// * `amount_per_claim` — fixed amount sent on every successful claim
    /// * `cooldown_seconds` — minimum time an address must wait between claims
    pub fn initialize(
        env: Env,
        admin: Address,
        token: Address,
        amount_per_claim: i128,
        cooldown_seconds: u64,
    ) {
        admin.require_auth();

        if amount_per_claim <= 0 {
            panic!("amount per claim must be positive");
        }

        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::Token, &token);
        env.storage()
            .instance()
            .set(&DataKey::AmountPerClaim, &amount_per_claim);
        env.storage()
            .instance()
            .set(&DataKey::CooldownSeconds, &cooldown_seconds);
    }

    /// Deposit tokens into the faucet.
    ///
    /// Must be called by the `admin`; may be called repeatedly to top up.
    pub fn fund(env: Env, amount: i128) {
        let admin: Address = env.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        let client = token::Client::new(&env, &token);
        client.transfer(&admin, &env.current_contract_address(), &amount);
    }

    /// Claim the fixed dispense amount.
    ///
    /// Requires authorization from `to`. Reverts if `to` claimed within the
    /// last `cooldown_seconds`.
    pub fn claim(env: Env, to: Address) -> i128 {
        to.require_auth();

        let now = env.ledger().timestamp();
        let cooldown: u64 = env
            .storage()
            .instance()
            .get(&DataKey::CooldownSeconds)
            .unwrap();

        let key = DataKey::LastClaim(to.clone());
        if let Some(last_claim) = env.storage().instance().get::<_, u64>(&key) {
            if now < last_claim + cooldown {
                panic!("cooldown not elapsed");
            }
        }

        env.storage().instance().set(&key, &now);

        let amount: i128 = env
            .storage()
            .instance()
            .get(&DataKey::AmountPerClaim)
            .unwrap();

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        let client = token::Client::new(&env, &token);
        client.transfer(&env.current_contract_address(), &to, &amount);

        amount
    }

    /// Return the timestamp at which `addr` may next successfully claim.
    pub fn next_claim_time(env: Env, addr: Address) -> u64 {
        let cooldown: u64 = env
            .storage()
            .instance()
            .get(&DataKey::CooldownSeconds)
            .unwrap();
        match env
            .storage()
            .instance()
            .get::<_, u64>(&DataKey::LastClaim(addr))
        {
            Some(last_claim) => last_claim + cooldown,
            None => 0,
        }
    }
}

#[cfg(test)]
mod test;
