//! Role-based access control: grant, revoke and check roles, with an admin
//! role that can administer the other roles.
//!
//! The access-control primitives are the reusable part — [`require_role`] is
//! the whole gate. The `mint`/`burn` ledger at the bottom of this file exists
//! only to give those roles something real to protect; replace it with your
//! own entrypoints.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{
    contract, contracterror, contractevent, contractimpl, contracttype, panic_with_error,
    symbol_short, Address, Env, Symbol,
};

/// Ledgers per day, assuming ~5s per ledger.
pub const DAY_IN_LEDGERS: u32 = 17280;
/// Persistent data TTL (30 days).
pub const PERSISTENT_TTL: u32 = 30 * DAY_IN_LEDGERS;
/// Threshold at which a read or write extends the TTL.
pub const PERSISTENT_TTL_THRESHOLD: u32 = PERSISTENT_TTL - DAY_IN_LEDGERS;

/// The bootstrap role. It administers itself and every role that has not been
/// given an explicit admin with `set_role_admin`.
pub const ADMIN_ROLE: Symbol = symbol_short!("admin");
/// Demo role gating `mint`.
pub const MINTER_ROLE: Symbol = symbol_short!("minter");
/// Demo role gating `burn`.
pub const BURNER_ROLE: Symbol = symbol_short!("burner");

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    /// Caller does not hold the role this entrypoint requires.
    Unauthorized = 1,
    /// The change would remove the last `ADMIN_ROLE` holder, leaving no one
    /// able to administer roles ever again.
    LastAdmin = 2,
    /// Amount must be positive.
    InvalidAmount = 3,
    /// Not enough balance to burn.
    InsufficientBalance = 4,
}

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    /// Whether an address currently holds a role. Absent means it does not.
    HasRole(Symbol, Address),
    /// The role permitted to grant and revoke a role. Absent means
    /// [`ADMIN_ROLE`].
    RoleAdmin(Symbol),
    /// How many addresses currently hold a role.
    RoleCount(Symbol),
    /// Demo ledger: balance of an address.
    Balance(Address),
    /// Demo ledger: tokens in circulation.
    TotalSupply,
}

// --- events -----------------------------------------------------------------
//
// Every role change is published so an indexer can follow who holds what
// without replaying storage. Fields marked `#[topic]` are indexable; the rest
// land in the event's data.

/// `role` was granted to `account`.
#[contractevent]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RoleGranted {
    #[topic]
    pub role: Symbol,
    pub account: Address,
}

/// `role` was revoked from `account`.
#[contractevent]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RoleRevoked {
    #[topic]
    pub role: Symbol,
    pub account: Address,
}

/// `role` is now administered by holders of `admin_role`.
#[contractevent]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RoleAdminChanged {
    #[topic]
    pub role: Symbol,
    pub admin_role: Symbol,
}

/// Demo ledger: `amount` was minted to `to`.
#[contractevent]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Mint {
    #[topic]
    pub to: Address,
    pub amount: i128,
}

/// Demo ledger: `amount` was burned from `from`.
#[contractevent]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Burn {
    #[topic]
    pub from: Address,
    pub amount: i128,
}

// --- role storage -----------------------------------------------------------
//
// Roles live in persistent storage and every read that finds an entry extends
// its TTL. That matters more here than for a balance: an expired role entry
// reads back as "does not hold the role", so a rarely-used admin would
// silently lose its powers.

fn read_has_role(env: &Env, role: &Symbol, account: &Address) -> bool {
    let key = DataKey::HasRole(role.clone(), account.clone());
    if let Some(held) = env.storage().persistent().get::<_, bool>(&key) {
        env.storage()
            .persistent()
            .extend_ttl(&key, PERSISTENT_TTL_THRESHOLD, PERSISTENT_TTL);
        held
    } else {
        false
    }
}

fn write_has_role(env: &Env, role: &Symbol, account: &Address) {
    let key = DataKey::HasRole(role.clone(), account.clone());
    env.storage().persistent().set(&key, &true);
    env.storage()
        .persistent()
        .extend_ttl(&key, PERSISTENT_TTL_THRESHOLD, PERSISTENT_TTL);
}

fn clear_has_role(env: &Env, role: &Symbol, account: &Address) {
    env.storage()
        .persistent()
        .remove(&DataKey::HasRole(role.clone(), account.clone()));
}

fn read_role_count(env: &Env, role: &Symbol) -> u32 {
    let key = DataKey::RoleCount(role.clone());
    if let Some(count) = env.storage().persistent().get::<_, u32>(&key) {
        env.storage()
            .persistent()
            .extend_ttl(&key, PERSISTENT_TTL_THRESHOLD, PERSISTENT_TTL);
        count
    } else {
        0
    }
}

fn write_role_count(env: &Env, role: &Symbol, count: u32) {
    let key = DataKey::RoleCount(role.clone());
    env.storage().persistent().set(&key, &count);
    env.storage()
        .persistent()
        .extend_ttl(&key, PERSISTENT_TTL_THRESHOLD, PERSISTENT_TTL);
}

fn read_role_admin(env: &Env, role: &Symbol) -> Symbol {
    let key = DataKey::RoleAdmin(role.clone());
    if let Some(admin_role) = env.storage().persistent().get::<_, Symbol>(&key) {
        env.storage()
            .persistent()
            .extend_ttl(&key, PERSISTENT_TTL_THRESHOLD, PERSISTENT_TTL);
        admin_role
    } else {
        ADMIN_ROLE
    }
}

/// Panics unless `caller` authorized this invocation *and* holds `role`.
///
/// This is the whole access-control gate — make it the first line of any
/// entrypoint you want to restrict:
///
/// ```ignore
/// pub fn set_fee(env: Env, caller: Address, fee: u32) {
///     require_role(&env, &caller, &MINTER_ROLE);
///     // ...
/// }
/// ```
fn require_role(env: &Env, caller: &Address, role: &Symbol) {
    caller.require_auth();
    if !read_has_role(env, role, caller) {
        panic_with_error!(env, Error::Unauthorized);
    }
}

/// Grant `role` to `account`, ignoring an account that already holds it.
///
/// Idempotence keeps the member count honest and means two admins granting the
/// same role concurrently cannot make one of them fail.
fn grant(env: &Env, role: &Symbol, account: &Address) {
    if read_has_role(env, role, account) {
        return;
    }
    write_has_role(env, role, account);
    write_role_count(env, role, read_role_count(env, role) + 1);
    RoleGranted {
        role: role.clone(),
        account: account.clone(),
    }
    .publish(env);
}

/// Revoke `role` from `account`, ignoring an account that does not hold it.
///
/// Refuses to remove the last `ADMIN_ROLE` holder: with no admins left, no
/// role could ever be granted again and the contract's role graph is frozen
/// for good.
fn revoke(env: &Env, role: &Symbol, account: &Address) {
    if !read_has_role(env, role, account) {
        return;
    }
    let count = read_role_count(env, role);
    if *role == ADMIN_ROLE && count <= 1 {
        panic_with_error!(env, Error::LastAdmin);
    }
    clear_has_role(env, role, account);
    write_role_count(env, role, count.saturating_sub(1));
    RoleRevoked {
        role: role.clone(),
        account: account.clone(),
    }
    .publish(env);
}

// --- demo ledger ------------------------------------------------------------

fn read_balance(env: &Env, account: &Address) -> i128 {
    let key = DataKey::Balance(account.clone());
    if let Some(balance) = env.storage().persistent().get::<_, i128>(&key) {
        env.storage()
            .persistent()
            .extend_ttl(&key, PERSISTENT_TTL_THRESHOLD, PERSISTENT_TTL);
        balance
    } else {
        0
    }
}

fn write_balance(env: &Env, account: &Address, amount: i128) {
    let key = DataKey::Balance(account.clone());
    env.storage().persistent().set(&key, &amount);
    env.storage()
        .persistent()
        .extend_ttl(&key, PERSISTENT_TTL_THRESHOLD, PERSISTENT_TTL);
}

fn read_total_supply(env: &Env) -> i128 {
    env.storage()
        .instance()
        .get(&DataKey::TotalSupply)
        .unwrap_or(0)
}

fn write_total_supply(env: &Env, amount: i128) {
    env.storage().instance().set(&DataKey::TotalSupply, &amount);
}

#[contract]
pub struct AccessControlContract;

#[contractimpl]
impl AccessControlContract {
    /// Deploy-time setup. Grants [`ADMIN_ROLE`] to `admin`, who can then grant
    /// every other role.
    pub fn __constructor(env: Env, admin: Address) {
        grant(&env, &ADMIN_ROLE, &admin);
    }

    /// Whether `account` currently holds `role`.
    pub fn has_role(env: Env, role: Symbol, account: Address) -> bool {
        read_has_role(&env, &role, &account)
    }

    /// The role whose holders may grant and revoke `role`. [`ADMIN_ROLE`]
    /// until changed with `set_role_admin`.
    pub fn get_role_admin(env: Env, role: Symbol) -> Symbol {
        read_role_admin(&env, &role)
    }

    /// How many addresses currently hold `role`.
    pub fn role_member_count(env: Env, role: Symbol) -> u32 {
        read_role_count(&env, &role)
    }

    /// Grant `role` to `account`. `caller` must hold `role`'s admin role.
    ///
    /// Granting a role the account already holds does nothing and emits no
    /// event.
    pub fn grant_role(env: Env, caller: Address, role: Symbol, account: Address) {
        let admin_role = read_role_admin(&env, &role);
        require_role(&env, &caller, &admin_role);
        grant(&env, &role, &account);
    }

    /// Revoke `role` from `account`. `caller` must hold `role`'s admin role.
    ///
    /// Revoking a role the account does not hold does nothing. Revoking the
    /// last [`ADMIN_ROLE`] holder fails with [`Error::LastAdmin`].
    pub fn revoke_role(env: Env, caller: Address, role: Symbol, account: Address) {
        let admin_role = read_role_admin(&env, &role);
        require_role(&env, &caller, &admin_role);
        revoke(&env, &role, &account);
    }

    /// Give up one of your own roles. Takes no admin role and can only ever
    /// affect the caller, so it cannot be used to strip someone else.
    pub fn renounce_role(env: Env, account: Address, role: Symbol) {
        account.require_auth();
        revoke(&env, &role, &account);
    }

    /// Hand administration of `role` to holders of `admin_role`.
    ///
    /// Requires [`ADMIN_ROLE`] — re-parenting the role graph stays a top-level
    /// privilege rather than something a delegated admin can do on its own.
    pub fn set_role_admin(env: Env, caller: Address, role: Symbol, admin_role: Symbol) {
        require_role(&env, &caller, &ADMIN_ROLE);
        let key = DataKey::RoleAdmin(role.clone());
        env.storage().persistent().set(&key, &admin_role);
        env.storage()
            .persistent()
            .extend_ttl(&key, PERSISTENT_TTL_THRESHOLD, PERSISTENT_TTL);
        RoleAdminChanged { role, admin_role }.publish(&env);
    }

    /// Demo entrypoint gated on [`MINTER_ROLE`] — see `require_role`.
    pub fn mint(env: Env, caller: Address, to: Address, amount: i128) {
        require_role(&env, &caller, &MINTER_ROLE);
        if amount <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }
        write_balance(&env, &to, read_balance(&env, &to) + amount);
        write_total_supply(&env, read_total_supply(&env) + amount);
        Mint { to, amount }.publish(&env);
    }

    /// Demo entrypoint gated on [`BURNER_ROLE`] — a second, separately
    /// administered role over the same ledger.
    pub fn burn(env: Env, caller: Address, from: Address, amount: i128) {
        require_role(&env, &caller, &BURNER_ROLE);
        if amount <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }
        let balance = read_balance(&env, &from);
        if balance < amount {
            panic_with_error!(&env, Error::InsufficientBalance);
        }
        write_balance(&env, &from, balance - amount);
        write_total_supply(&env, read_total_supply(&env) - amount);
        Burn { from, amount }.publish(&env);
    }

    /// Demo ledger: balance of `account`.
    pub fn balance(env: Env, account: Address) -> i128 {
        read_balance(&env, &account)
    }

    /// Demo ledger: tokens in circulation.
    pub fn total_supply(env: Env) -> i128 {
        read_total_supply(&env)
    }
}

#[cfg(test)]
mod test;
