//! Lottery / raffle using a commit-reveal scheme for randomness.
//!
//! * **Enter** — during the commit phase, entrants submit a commitment
//!   (`sha256(nonce)`) that hides a secret nonce they will reveal later.
//! * **Reveal** — during the reveal phase, entrants reveal their nonce; the
//!   contract checks it hashes to their commitment.
//! * **Draw** — after the reveal phase ends, anyone can call `draw`, which
//!   XORs every revealed nonce into a single seed and picks the winner from
//!   the entrants who successfully revealed. Entrants who never reveal
//!   forfeit the draw — this is what makes the scheme resistant to a single
//!   party biasing the outcome, since no one controls the final seed alone.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, Address, Bytes, BytesN, Env, Vec};

#[contracttype]
pub enum DataKey {
    Admin,
    CommitDeadline,
    RevealDeadline,
    Entrants,
    Commitment(Address),
    Revealed(Address),
    Winner,
    Drawn,
}

#[contract]
pub struct LotteryContract;

#[contractimpl]
impl LotteryContract {
    /// Initialize the lottery.
    ///
    /// * `admin` — address that configures the lottery
    /// * `commit_deadline` — ledger timestamp after which entries close
    /// * `reveal_deadline` — ledger timestamp after which reveals close and
    ///   the winner can be drawn
    pub fn initialize(env: Env, admin: Address, commit_deadline: u64, reveal_deadline: u64) {
        admin.require_auth();

        if reveal_deadline <= commit_deadline {
            panic!("reveal deadline must be after commit deadline");
        }

        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage()
            .instance()
            .set(&DataKey::CommitDeadline, &commit_deadline);
        env.storage()
            .instance()
            .set(&DataKey::RevealDeadline, &reveal_deadline);
        env.storage()
            .instance()
            .set(&DataKey::Entrants, &Vec::<Address>::new(&env));
        env.storage().instance().set(&DataKey::Drawn, &false);
    }

    /// Enter the lottery with a commitment to a secret nonce.
    ///
    /// `commitment` must equal `sha256(nonce)` for the nonce that will be
    /// passed to `reveal` later. Must be called before the commit deadline.
    pub fn enter(env: Env, entrant: Address, commitment: BytesN<32>) {
        entrant.require_auth();

        let now = env.ledger().timestamp();
        let commit_deadline: u64 = env
            .storage()
            .instance()
            .get(&DataKey::CommitDeadline)
            .unwrap();
        if now >= commit_deadline {
            panic!("commit phase has ended");
        }

        let key = DataKey::Commitment(entrant.clone());
        if env.storage().instance().has(&key) {
            panic!("already entered");
        }
        env.storage().instance().set(&key, &commitment);

        let mut entrants: Vec<Address> = env
            .storage()
            .instance()
            .get(&DataKey::Entrants)
            .unwrap();
        entrants.push_back(entrant);
        env.storage().instance().set(&DataKey::Entrants, &entrants);
    }

    /// Reveal the nonce behind a prior commitment.
    ///
    /// Must be called during the reveal window (after the commit deadline,
    /// before the reveal deadline) with the nonce whose sha256 matches the
    /// commitment submitted in `enter`.
    pub fn reveal(env: Env, entrant: Address, nonce: BytesN<32>) {
        entrant.require_auth();

        let now = env.ledger().timestamp();
        let commit_deadline: u64 = env
            .storage()
            .instance()
            .get(&DataKey::CommitDeadline)
            .unwrap();
        let reveal_deadline: u64 = env
            .storage()
            .instance()
            .get(&DataKey::RevealDeadline)
            .unwrap();
        if now < commit_deadline || now >= reveal_deadline {
            panic!("not in reveal phase");
        }

        let commitment: BytesN<32> = env
            .storage()
            .instance()
            .get(&DataKey::Commitment(entrant.clone()))
            .unwrap_or_else(|| panic!("no entry to reveal"));

        let revealed_key = DataKey::Revealed(entrant.clone());
        if env.storage().instance().has(&revealed_key) {
            panic!("already revealed");
        }

        let nonce_bytes: Bytes = nonce.clone().into();
        let computed = env.crypto().sha256(&nonce_bytes).to_bytes();
        if computed != commitment {
            panic!("nonce does not match commitment");
        }

        env.storage().instance().set(&revealed_key, &nonce);
    }

    /// Draw the winner from the entrants who successfully revealed.
    ///
    /// Callable by anyone once the reveal deadline has passed. The random
    /// seed is derived by XOR-ing every revealed nonce together, so no
    /// single entrant controls the outcome.
    pub fn draw(env: Env) -> Address {
        let now = env.ledger().timestamp();
        let reveal_deadline: u64 = env
            .storage()
            .instance()
            .get(&DataKey::RevealDeadline)
            .unwrap();
        if now < reveal_deadline {
            panic!("reveal phase has not ended");
        }

        let drawn: bool = env.storage().instance().get(&DataKey::Drawn).unwrap();
        if drawn {
            panic!("winner already drawn");
        }

        let entrants: Vec<Address> = env.storage().instance().get(&DataKey::Entrants).unwrap();

        let mut revealed_entrants: Vec<Address> = Vec::new(&env);
        let mut seed = [0_u8; 32];
        for entrant in entrants.iter() {
            let revealed_key = DataKey::Revealed(entrant.clone());
            if let Some(nonce) = env.storage().instance().get::<_, BytesN<32>>(&revealed_key) {
                let nonce_arr = nonce.to_array();
                for i in 0..32 {
                    seed[i] ^= nonce_arr[i];
                }
                revealed_entrants.push_back(entrant);
            }
        }

        if revealed_entrants.is_empty() {
            panic!("no valid reveals");
        }

        let mut index_bytes = [0_u8; 8];
        index_bytes.copy_from_slice(&seed[0..8]);
        let index = (u64::from_be_bytes(index_bytes) % revealed_entrants.len() as u64) as u32;

        let winner = revealed_entrants.get(index).unwrap();

        env.storage().instance().set(&DataKey::Winner, &winner);
        env.storage().instance().set(&DataKey::Drawn, &true);

        winner
    }

    /// Return the drawn winner. Panics if the winner has not been drawn yet.
    pub fn get_winner(env: Env) -> Address {
        env.storage()
            .instance()
            .get(&DataKey::Winner)
            .unwrap_or_else(|| panic!("winner not drawn yet"))
    }
}

#[cfg(test)]
mod test;
