#!/usr/bin/env bash
# Regenerate homebrew-tap/Formula/soroban-forge.rb for a given release.
#
# The formula is generated wholesale from the template below rather than
# patched in place, so the checked-in formula and this script can never drift
# apart.  This script is the single source of truth for the formula.
#
# Usage:
#   scripts/update-homebrew-formula.sh --version 0.2.0 [options]
#
# Options:
#   --version X.Y.Z      Release version, without the leading `v`. Required.
#   --checksums FILE     `shasum -a 256` output covering the release archives.
#                        Any target missing from the file gets a PLACEHOLDER
#                        sha256 instead. Defaults to placeholders throughout.
#   --output FILE        Where to write the formula.
#                        Default: homebrew-tap/Formula/soroban-forge.rb
#   --check              Print the formula to stdout and exit without writing.
#
# Example (after a release has been published):
#   shasum -a 256 soroban-forge-0.2.0-*.tar.gz > SHA256SUMS.txt
#   scripts/update-homebrew-formula.sh --version 0.2.0 --checksums SHA256SUMS.txt

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

VERSION=""
CHECKSUMS=""
OUTPUT="$REPO_ROOT/homebrew-tap/Formula/soroban-forge.rb"
CHECK_ONLY=0

die() {
  echo "error: $*" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      [[ $# -ge 2 ]] || die "--version requires an argument"
      VERSION="$2"
      shift 2
      ;;
    --checksums)
      [[ $# -ge 2 ]] || die "--checksums requires an argument"
      CHECKSUMS="$2"
      shift 2
      ;;
    --output)
      [[ $# -ge 2 ]] || die "--output requires an argument"
      OUTPUT="$2"
      shift 2
      ;;
    --check)
      CHECK_ONLY=1
      shift
      ;;
    -h | --help)
      sed -n '2,25p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

[[ -n "$VERSION" ]] || die "--version is required (e.g. --version 0.2.0)"

# Reject a leading `v` so the generated URLs never end up as `.../vv0.2.0/`.
[[ "$VERSION" != v* ]] || die "--version must not include the leading 'v' (got '$VERSION')"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-+][0-9A-Za-z.-]+)?$ ]] ||
  die "--version must be a semver string like 0.2.0 (got '$VERSION')"

if [[ -n "$CHECKSUMS" && ! -f "$CHECKSUMS" ]]; then
  die "checksums file not found: $CHECKSUMS"
fi

# Look up the sha256 of a release archive in the checksums file.  `shasum` and
# `sha256sum` both emit `<sha>  <name>`; the name may carry a directory prefix
# depending on where the command was run, so match on the basename only.
sha_for() {
  local target="$1"
  local archive="soroban-forge-${VERSION}-${target}.tar.gz"
  local placeholder
  # PLACEHOLDER_SHA256_X86_64_APPLE_DARWIN and friends.
  placeholder="PLACEHOLDER_SHA256_$(echo "$target" | tr '[:lower:]-' '[:upper:]_')"

  if [[ -z "$CHECKSUMS" ]]; then
    echo "$placeholder"
    return
  fi

  local sha
  sha="$(awk -v want="$archive" '
    {
      n = $NF
      sub(/^\*/, "", n)          # sha256sum --binary marks names with a "*"
      sub(/^.*\//, "", n)        # strip any directory prefix
      if (n == want) { print $1; exit }
    }
  ' "$CHECKSUMS")"

  if [[ -z "$sha" ]]; then
    echo "warning: no checksum for $archive in $CHECKSUMS — using a placeholder" >&2
    echo "$placeholder"
  else
    echo "$sha"
  fi
}

SHA_MACOS_ARM="$(sha_for aarch64-apple-darwin)"
SHA_MACOS_INTEL="$(sha_for x86_64-apple-darwin)"
SHA_LINUX_ARM="$(sha_for aarch64-unknown-linux-gnu)"
SHA_LINUX_INTEL="$(sha_for x86_64-unknown-linux-gnu)"

read -r -d '' FORMULA <<FORMULA_EOF || true
# typed: false
# frozen_string_literal: true

# Homebrew formula for soroban-forge.
# Hosted in the tap repo: https://github.com/soroban-forge-labs/homebrew-tap
#
# DO NOT EDIT BY HAND — generated by \`scripts/update-homebrew-formula.sh\` in
# the main repository. The copy checked in there carries placeholder checksums;
# the \`release\` workflow re-renders it with the real ones on every tag and
# publishes that version to the tap.
class SorobanForge < Formula
  desc "Scaffolding, test-harness and CI toolkit for Soroban smart contracts on Stellar"
  homepage "https://github.com/soroban-forge-labs/soroban-forge"
  version "${VERSION}"
  license "Apache-2.0"

  # ---------------------------------------------------------------------------
  # Release archives — one per supported platform.
  # Each archive is a .tar.gz containing a single pre-compiled \`soroban-forge\`
  # binary, so installing needs no Rust toolchain and no build step.
  # ---------------------------------------------------------------------------

  on_macos do
    on_arm do
      url "https://github.com/soroban-forge-labs/soroban-forge/releases/download/v#{version}/soroban-forge-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_MACOS_ARM}"
    end

    on_intel do
      url "https://github.com/soroban-forge-labs/soroban-forge/releases/download/v#{version}/soroban-forge-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_MACOS_INTEL}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/soroban-forge-labs/soroban-forge/releases/download/v#{version}/soroban-forge-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_LINUX_ARM}"
    end

    on_intel do
      url "https://github.com/soroban-forge-labs/soroban-forge/releases/download/v#{version}/soroban-forge-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_LINUX_INTEL}"
    end
  end

  def install
    bin.install "soroban-forge"

    # \`soroban-forge completions <shell>\` writes the script to stdout. The CLI
    # handles this before any network or config work, so it is safe to run
    # inside Homebrew's sandbox.
    generate_completions_from_executable(bin/"soroban-forge", "completions")

    # \`soroban-forge man --out-dir DIR\` writes one roff page per subcommand.
    # Best-effort via \`quiet_system\`: man pages are a convenience and must
    # never be the reason \`brew install\` fails. The env var suppresses the
    # background release check so the sandboxed build never needs the network.
    man_generated = with_env("SOROBAN_FORGE_NO_UPDATE_CHECK" => "1") do
      quiet_system bin/"soroban-forge", "man", "--out-dir", "manpages"
    end
    man1.install Dir["manpages/*.1"] if man_generated
  end

  test do
    # The binary must report the version this formula claims to have installed.
    assert_match version.to_s, shell_output("#{bin}/soroban-forge --version")

    # Completions must generate, since \`install\` depends on them.
    assert_match "soroban-forge", shell_output("#{bin}/soroban-forge completions bash")

    # And the CLI must actually scaffold a project. \`--no-git\` keeps the test
    # hermetic (no git identity required) and the env var suppresses the
    # background release check so the test never needs the network.
    with_env("SOROBAN_FORGE_NO_UPDATE_CHECK" => "1") do
      system bin/"soroban-forge", "new", "demo", "--template", "hello-world", "--no-git"
    end
    assert_predicate testpath/"demo/Cargo.toml", :exist?
  end
end
FORMULA_EOF

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  printf '%s\n' "$FORMULA"
  exit 0
fi

mkdir -p "$(dirname "$OUTPUT")"
printf '%s\n' "$FORMULA" > "$OUTPUT"
echo "wrote $OUTPUT (version $VERSION)"

if [[ "$FORMULA" == *PLACEHOLDER_SHA256_* ]]; then
  echo "note: the formula still contains placeholder sha256 values." >&2
  echo "      Re-run with --checksums once the release archives are published." >&2
fi
