//! Wrapped asset — mints a wrapper balance on deposit, burns it on withdraw,
//! always 1:1 with an underlying SEP-41 token locked in the contract.
//!
//! * **Wrap** — deposit `amount` of the underlying token; the contract locks
//!   it and credits the caller's wrapper balance by `amount`.
//! * **Unwrap** — burn `amount` of wrapper balance; the contract releases
//!   `amount` of the underlying token back to the caller.
//! * **Conservation** — total wrapper supply always equals the underlying
//!   token balance held by this contract.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, token, Address, Env};

#[contracttype]
pub enum DataKey {
    Underlying,
    TotalSupply,
    Balance(Address),
}

#[contract]
pub struct WrappedAssetContract;

#[contractimpl]
impl WrappedAssetContract {
    /// Initialize the wrapper for a given underlying SEP-41 token.
    pub fn initialize(env: Env, underlying: Address) {
        env.storage().instance().set(&DataKey::Underlying, &underlying);
        env.storage().instance().set(&DataKey::TotalSupply, &0_i128);
    }

    /// Deposit `amount` of the underlying token and mint the same amount of
    /// wrapper balance to `from`.
    pub fn wrap(env: Env, from: Address, amount: i128) -> i128 {
        from.require_auth();

        if amount <= 0 {
            panic!("amount must be positive");
        }

        let underlying: Address = env.storage().instance().get(&DataKey::Underlying).unwrap();
        let client = token::Client::new(&env, &underlying);
        client.transfer(&from, &env.current_contract_address(), &amount);

        let balance_key = DataKey::Balance(from.clone());
        let balance: i128 = env.storage().instance().get(&balance_key).unwrap_or(0);
        env.storage()
            .instance()
            .set(&balance_key, &(balance + amount));

        let total_supply: i128 = env.storage().instance().get(&DataKey::TotalSupply).unwrap();
        let new_total = total_supply + amount;
        env.storage()
            .instance()
            .set(&DataKey::TotalSupply, &new_total);

        new_total
    }

    /// Burn `amount` of wrapper balance from `from` and release the same
    /// amount of the underlying token back to them.
    pub fn unwrap(env: Env, from: Address, amount: i128) -> i128 {
        from.require_auth();

        if amount <= 0 {
            panic!("amount must be positive");
        }

        let balance_key = DataKey::Balance(from.clone());
        let balance: i128 = env.storage().instance().get(&balance_key).unwrap_or(0);
        if balance < amount {
            panic!("insufficient wrapper balance");
        }
        env.storage()
            .instance()
            .set(&balance_key, &(balance - amount));

        let total_supply: i128 = env.storage().instance().get(&DataKey::TotalSupply).unwrap();
        let new_total = total_supply - amount;
        env.storage()
            .instance()
            .set(&DataKey::TotalSupply, &new_total);

        let underlying: Address = env.storage().instance().get(&DataKey::Underlying).unwrap();
        let client = token::Client::new(&env, &underlying);
        client.transfer(&env.current_contract_address(), &from, &amount);

        new_total
    }

    /// The wrapper balance held by `id`.
    pub fn balance_of(env: Env, id: Address) -> i128 {
        env.storage()
            .instance()
            .get(&DataKey::Balance(id))
            .unwrap_or(0)
    }

    /// The total wrapper supply currently outstanding.
    pub fn total_supply(env: Env) -> i128 {
        env.storage().instance().get(&DataKey::TotalSupply).unwrap()
    }
}

#[cfg(test)]
mod test;
