//! Streaming payments — a token released continuously over time.
//!
//! Tokens are locked in the contract and become claimable by a recipient
//! pro-rata to elapsed time since the stream started:
//!
//! * **Linear release** — tokens vest continuously at a constant rate from
//!   `initialize` until `duration_seconds` has elapsed.
//! * **Claim** — the recipient may call `claim` at any point, including
//!   mid-stream; the contract transfers the newly streamed amount since the
//!   last claim.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, token, Address, Env};

#[contracttype]
pub enum DataKey {
    Sender,
    Token,
    Recipient,
    Start,
    End,
    TotalAmount,
    Claimed,
}

#[contract]
pub struct StreamingContract;

#[contractimpl]
impl StreamingContract {
    /// Initialize the stream.
    ///
    /// * `sender` — address that will fund the contract with tokens
    /// * `token` — contract address of the SEP-41 token to stream
    /// * `recipient` — address that receives streamed tokens
    /// * `duration_seconds` — seconds over which `total_amount` streams
    /// * `total_amount` — total tokens to release over the stream
    pub fn initialize(
        env: Env,
        sender: Address,
        token: Address,
        recipient: Address,
        duration_seconds: u64,
        total_amount: i128,
    ) {
        sender.require_auth();

        if total_amount <= 0 {
            panic!("total amount must be positive");
        }
        if duration_seconds == 0 {
            panic!("duration must be positive");
        }

        let now = env.ledger().timestamp();

        env.storage().instance().set(&DataKey::Sender, &sender);
        env.storage().instance().set(&DataKey::Token, &token);
        env.storage()
            .instance()
            .set(&DataKey::Recipient, &recipient);
        env.storage().instance().set(&DataKey::Start, &now);
        env.storage()
            .instance()
            .set(&DataKey::End, &(now + duration_seconds));
        env.storage()
            .instance()
            .set(&DataKey::TotalAmount, &total_amount);
        env.storage().instance().set(&DataKey::Claimed, &0_i128);
    }

    /// Deposit the full stream amount into this contract.
    ///
    /// Must be called by the `sender` after `initialize`.
    pub fn fund(env: Env) {
        let sender: Address = env.storage().instance().get(&DataKey::Sender).unwrap();
        sender.require_auth();

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        let total_amount: i128 = env.storage().instance().get(&DataKey::TotalAmount).unwrap();

        let client = token::Client::new(&env, &token);
        client.transfer(&sender, &env.current_contract_address(), &total_amount);
    }

    /// Return the amount of tokens streamed so far according to elapsed time.
    pub fn get_streamed_amount(env: Env) -> i128 {
        let now = env.ledger().timestamp();
        let start: u64 = env.storage().instance().get(&DataKey::Start).unwrap();
        let end: u64 = env.storage().instance().get(&DataKey::End).unwrap();
        let total_amount: i128 = env.storage().instance().get(&DataKey::TotalAmount).unwrap();

        if now <= start {
            return 0;
        }
        if now >= end {
            return total_amount;
        }

        // Linear interpolation: total * (now - start) / (end - start)
        let elapsed = now - start;
        let duration = end - start;
        (total_amount as u128 * elapsed as u128 / duration as u128) as i128
    }

    /// Return the amount the recipient can currently claim
    /// (streamed minus already claimed).
    pub fn get_claimable_amount(env: Env) -> i128 {
        let streamed = Self::get_streamed_amount(env.clone());
        let claimed: i128 = env.storage().instance().get(&DataKey::Claimed).unwrap();
        streamed - claimed
    }

    /// Claim all currently streamed tokens for the recipient.
    ///
    /// Transfers the newly streamed amount (since the last claim) to the
    /// recipient. Can be called multiple times, including mid-stream.
    pub fn claim(env: Env) -> i128 {
        let recipient: Address = env.storage().instance().get(&DataKey::Recipient).unwrap();
        recipient.require_auth();

        let claimable = Self::get_claimable_amount(env.clone());
        if claimable <= 0 {
            panic!("nothing to claim");
        }

        let claimed: i128 = env.storage().instance().get(&DataKey::Claimed).unwrap();
        env.storage()
            .instance()
            .set(&DataKey::Claimed, &(claimed + claimable));

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        let client = token::Client::new(&env, &token);
        client.transfer(&env.current_contract_address(), &recipient, &claimable);

        claimable
    }
}

#[cfg(test)]
mod test;
