//! Payment splitter — distributes received funds to payees by fixed shares.
//!
//! Payees and their shares are fixed at initialization. Every deposit is
//! credited to the pool, and each payee can withdraw their proportional cut
//! at any time:
//!
//! * **Shares** — each payee holds a fixed number of shares out of
//!   `total_shares`; a payee is entitled to
//!   `total_received * share / total_shares` over the contract's lifetime.
//! * **Pull payments** — nothing is pushed on deposit. `release` transfers
//!   what a payee has earned but not yet withdrawn, so a failing payee can
//!   never block a deposit.
//! * **Rounding** — entitlements are floor-divided, so up to
//!   `total_shares - 1` stray units can stay in the contract. `undistributed`
//!   reports that dust; it is released as later deposits push each payee's
//!   entitlement over the next whole unit.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, token, Address, Env, Vec};

#[contracttype]
pub enum DataKey {
    Token,
    Payees,
    TotalShares,
    /// Shares held by one payee.
    Shares(Address),
    /// Amount already withdrawn by one payee.
    Released(Address),
    /// Everything ever deposited into the splitter.
    TotalReceived,
    /// Everything ever withdrawn by payees.
    TotalReleased,
}

#[contract]
pub struct PaymentSplitterContract;

#[contractimpl]
impl PaymentSplitterContract {
    /// Configure the splitter.
    ///
    /// * `token`  — contract address of the SEP-41 token being split
    /// * `payees` — addresses receiving a cut, in any order
    /// * `shares` — share count per payee, positionally matching `payees`
    ///
    /// Panics when the two vectors differ in length, when `payees` is empty,
    /// when a payee appears twice, or when any share is zero.
    pub fn initialize(env: Env, token: Address, payees: Vec<Address>, shares: Vec<u32>) {
        if payees.is_empty() {
            panic!("at least one payee is required");
        }
        if payees.len() != shares.len() {
            panic!("payees and shares must have the same length");
        }

        let mut total_shares: u32 = 0;
        for i in 0..payees.len() {
            let payee = payees.get_unchecked(i);
            let share = shares.get_unchecked(i);
            if share == 0 {
                panic!("share must be positive");
            }
            if env
                .storage()
                .instance()
                .has(&DataKey::Shares(payee.clone()))
            {
                panic!("duplicate payee");
            }
            env.storage()
                .instance()
                .set(&DataKey::Shares(payee.clone()), &share);
            env.storage()
                .instance()
                .set(&DataKey::Released(payee), &0_i128);
            total_shares += share;
        }

        env.storage().instance().set(&DataKey::Token, &token);
        env.storage().instance().set(&DataKey::Payees, &payees);
        env.storage()
            .instance()
            .set(&DataKey::TotalShares, &total_shares);
        env.storage()
            .instance()
            .set(&DataKey::TotalReceived, &0_i128);
        env.storage()
            .instance()
            .set(&DataKey::TotalReleased, &0_i128);
    }

    /// Deposit `amount` tokens from `from` into the splitter.
    ///
    /// Deposits are tracked explicitly rather than inferred from the
    /// contract's balance, so a stray direct transfer can never shift what
    /// payees are owed.
    pub fn deposit(env: Env, from: Address, amount: i128) {
        from.require_auth();
        if amount <= 0 {
            panic!("deposit must be positive");
        }

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        let splitter = env.current_contract_address();
        token::Client::new(&env, &token).transfer(&from, &splitter, &amount);

        let received: i128 = env
            .storage()
            .instance()
            .get(&DataKey::TotalReceived)
            .unwrap();
        env.storage()
            .instance()
            .set(&DataKey::TotalReceived, &(received + amount));
    }

    /// Shares held by `payee`. Panics for an address that is not a payee.
    pub fn shares(env: Env, payee: Address) -> u32 {
        env.storage()
            .instance()
            .get(&DataKey::Shares(payee))
            .unwrap_or_else(|| panic!("not a payee"))
    }

    /// Total the payee has already withdrawn.
    pub fn released(env: Env, payee: Address) -> i128 {
        Self::shares(env.clone(), payee.clone());
        env.storage()
            .instance()
            .get(&DataKey::Released(payee))
            .unwrap_or(0)
    }

    /// Everything the payee has earned over the splitter's lifetime,
    /// floor-divided: `total_received * share / total_shares`.
    pub fn earned(env: Env, payee: Address) -> i128 {
        let share = Self::shares(env.clone(), payee) as i128;
        let total_shares: i128 = Self::total_shares(env.clone()) as i128;
        let received = Self::total_received(env);
        received * share / total_shares
    }

    /// What `payee` can withdraw right now — earned minus already released.
    pub fn releasable(env: Env, payee: Address) -> i128 {
        Self::earned(env.clone(), payee.clone()) - Self::released(env, payee)
    }

    /// Transfer everything currently owed to `payee`.
    ///
    /// Callable by anyone — the funds always go to the payee — so a keeper or
    /// the payee themselves can trigger it. Returns the amount transferred
    /// and panics when nothing is owed.
    pub fn release(env: Env, payee: Address) -> i128 {
        let amount = Self::releasable(env.clone(), payee.clone());
        if amount <= 0 {
            panic!("nothing to release");
        }

        let released: i128 = Self::released(env.clone(), payee.clone());
        env.storage()
            .instance()
            .set(&DataKey::Released(payee.clone()), &(released + amount));

        let total_released: i128 = Self::total_released(env.clone());
        env.storage()
            .instance()
            .set(&DataKey::TotalReleased, &(total_released + amount));

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        token::Client::new(&env, &token).transfer(&env.current_contract_address(), &payee, &amount);

        amount
    }

    /// All configured payees.
    pub fn payees(env: Env) -> Vec<Address> {
        env.storage().instance().get(&DataKey::Payees).unwrap()
    }

    /// Sum of every payee's shares.
    pub fn total_shares(env: Env) -> u32 {
        env.storage().instance().get(&DataKey::TotalShares).unwrap()
    }

    /// Everything ever deposited.
    pub fn total_received(env: Env) -> i128 {
        env.storage()
            .instance()
            .get(&DataKey::TotalReceived)
            .unwrap()
    }

    /// Everything ever withdrawn by payees.
    pub fn total_released(env: Env) -> i128 {
        env.storage()
            .instance()
            .get(&DataKey::TotalReleased)
            .unwrap()
    }

    /// Rounding dust: deposits that no payee is entitled to yet because
    /// entitlements are floor-divided.
    pub fn undistributed(env: Env) -> i128 {
        let payees = Self::payees(env.clone());
        let mut earned = 0_i128;
        for payee in payees.iter() {
            earned += Self::earned(env.clone(), payee);
        }
        Self::total_received(env) - earned
    }
}

#[cfg(test)]
mod test;
